services:
  mysql:
    image: mysql:8
    volumes:
      - mysqldata:/var/lib/mysql
    env_file:
      - mysql.env
    ports:
      - "3306:3306"
  redis:
    image: redis:7.4.1
volumes:
  mysqldata: