services:
  mysql:
    image: mysql:8
    volumes:
      - mysqldata:/var/lib/mysql
    env_file:
      - mysql.env
    ports:
      - "3306:3306"
  redis:
    image: redis:7.4.1
  mongo:
    image: mongodb/mongodb-community-server
    ports:
      - "8081:8081"
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: henning
      MONGO_INITDB_ROOT_PASSWORD: pressening
volumes:
  mysqldata: